# Generated by Django 4.2.2 on 2024-04-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, default='18977803', max_length=8, null=True, verbose_name='код подтверждения почты'),
        ),
    ]
