# Generated by Django 4.2.2 on 2024-04-02 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=15, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='аватар')),
                ('description', models.TextField(verbose_name='краткое описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано на сайте')),
                ('name_category', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='staff.rank', verbose_name='наименование категории')),
            ],
            options={
                'verbose_name': 'персонал',
                'verbose_name_plural': 'персонал',
            },
        ),
    ]
