# Generated by Django 4.2.2 on 2024-04-02 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_alter_product_is_published_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(upload_to='media/', verbose_name='изображение')),
                ('price', models.IntegerField(verbose_name='цена за услугу')),
                ('date_base', models.DateField(blank=True, null=True, verbose_name='дата создания')),
                ('date_change', models.DateField(blank=True, null=True, verbose_name='дата изменения')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано на сайте')),
                ('category', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='наименование категории')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'permissions': [('set_published_status', 'can publish product')],
            },
        ),
        migrations.RemoveField(
            model_name='version',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
