# Generated by Django 4.2.2 on 2024-04-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_service_remove_version_product_delete_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': [('set_published_status', 'can publish service')], 'verbose_name': 'медицинская услуга', 'verbose_name_plural': 'медицинские услуги'},
        ),
    ]
