# Generated by Django 4.2.2 on 2024-04-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_remove_record_image_remove_record_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='description',
        ),
        migrations.RemoveField(
            model_name='record',
            name='views_count',
        ),
        migrations.AddField(
            model_name='record',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='возраст'),
        ),
        migrations.AddField(
            model_name='record',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='пол'),
        ),
        migrations.AddField(
            model_name='record',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='record',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='телефон'),
        ),
        migrations.AddField(
            model_name='record',
            name='surname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя'),
        ),
    ]
