# Generated by Django 4.2.2 on 2024-04-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_remove_record_description_remove_record_views_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_recorded',
            field=models.DateField(blank=True, null=True, verbose_name='дата записи'),
        ),
        migrations.AddField(
            model_name='record',
            name='time_recorded',
            field=models.TimeField(blank=True, null=True, verbose_name='время записи'),
        ),
    ]
